## PCXT-EGA for MEGA65 (PCXT-EGA-MEGA65)
##
## Core specific constraints
##
## This machine is based on MiSTer-devel/PCXT-EGA_MiSTer
## Powered by MiSTer2MEGA65
## MEGA65 port done by silent-command in 2026 and licensed under GPL v3
##
## Source of every constraint below: docs/clocks-and-timing-constraints.md,
## which maps the core's Quartus SYSTEM.sdc onto Vivado. Sections 2 (false
## paths between chipset and video, max-delay on the EGA I/O synchronisers)
## are added once pcxt_core.sv exists and the register names are known.


## Name Autogenerated Clocks
## Important: Using them in subsequent statements, e.g. clock dividers requires that they
## have been named/defined here before
## otherwise Vivado does not find the pins)

# MMCM A: 630 MHz VCO, NTSC colour-burst family (CORE/vhdl/clk.vhd)
create_generated_clock -name clk_28      [get_pins CORE/clk_gen/i_mmcm_a/CLKOUT0]   ;# 28.636364 MHz
create_generated_clock -name clk_57      [get_pins CORE/clk_gen/i_mmcm_a/CLKOUT1]   ;# 57.272727 MHz
create_generated_clock -name clk_57_ps   [get_pins CORE/clk_gen/i_mmcm_a/CLKOUT2]   ;# 57.272727 MHz, +90 deg
create_generated_clock -name clk_25      [get_pins CORE/clk_gen/i_mmcm_a/CLKOUT3]   ;# 25.2 MHz
create_generated_clock -name clk_14      [get_pins CORE/clk_gen/i_mmcm_a/CLKOUT4]   ;# 14.318182 MHz

# MMCM B: 1000 MHz VCO, CPU and chipset
create_generated_clock -name clk_100     [get_pins CORE/clk_gen/i_mmcm_b/CLKOUT0]   ;# 100 MHz, MCL86
create_generated_clock -name clk_50      [get_pins CORE/clk_gen/i_mmcm_b/CLKOUT1]   ;# 50 MHz, chipset (main_clk)

## Clock groups
## On MiSTer the chipset/CPU pair and the video family were declared exclusive
## and every chipset<->video path was a false path (SYSTEM.sdc). The RTL
## synchronises those crossings itself (docs section 3.1). clk_100 and clk_50
## stay related, as do 28.636/57.273/57.273+90/14.318. clk_25 is only used
## behind the video clock mux and has no clean ratio to the others, so it is
## its own group; without this Vivado would time 25.2<->57.27 at the 630 MHz
## common period.
set_clock_groups -asynchronous \
    -group [get_clocks {clk_100 clk_50}] \
    -group [get_clocks {clk_28 clk_57 clk_57_ps clk_14}] \
    -group [get_clocks {clk_25}]

# The memory backend crosses into the framework's HyperRAM clock through the
# framework's avm_fifo (xpm async FIFO); no timed paths between the two.
set_clock_groups -asynchronous -group [get_clocks {clk_100 clk_50}] -group [get_clocks {hr_clk hr_clk_del}]
